import com.google.gson.Gson;
import com.thoughtworks.xstream.XStream;
import java.awt.*;
import java.beans.ExceptionListener;
import java.beans.XMLEncoder;
import java.io.*;
import java.util.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class MainWindow extends javax.swing.JFrame {
    Vector<GrObject> OBJ=new Vector();
    /** Creates new form Wnd */
    public MainWindow() {
        initComponents();
        TYPE.add("Окружность");
        TYPE.add("Звезда");
        TT.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateRadius();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateRadius();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateRadius();
            }
        });
        this.setBounds(300,200,580,440);
    }
    
    private void updateRadius() {
        int r = 70;
        try {
            r = Integer.parseInt(TT.getText());
        } catch (NumberFormatException ex) {}
        radius = r;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TXT = new javax.swing.JTextArea();
        TT = new javax.swing.JTextField();
        TYPE = new java.awt.Choice();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TXT.setEditable(false);
        TXT.setColumns(20);
        TXT.setRows(5);
        TXT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TXTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TXT);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 44, 540, 311);

        TT.setText("70");
        TT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTActionPerformed(evt);
            }
        });
        getContentPane().add(TT);
        TT.setBounds(150, 10, 400, 22);
        getContentPane().add(TYPE);
        TYPE.setBounds(10, 10, 120, 20);

        jMenu1.setText("Файл");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Открыть двоичный файл...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Сохранить двоичный файл...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Открыть текстовый файл...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Сохранить текстовый файл...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem6.setText("Load Serial");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Save Serial");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Load XML");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Save XML");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuItem10.setText("Load JSON");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setText("SaveJSON");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TXTMouseClicked
        int xx=evt.getX();
        int yy=evt.getY();
        GrObject pp;
        switch (evt.getButton()){
case 1:
        if (TYPE.getSelectedIndex()==0)
            pp=new Circle(xx,yy,radius,TXT);
        else
            pp=new Zwezda(xx,yy,radius,6,TXT);
        OBJ.add(pp);
        new Thread(pp).start();
        break;
case 3:
        int nn=OBJ.size();
        for (int i=0;i<nn;i++){
            pp=(GrObject)OBJ.get(i);
            if (pp.inside(xx, yy)) {
                pp.stop=true;
                OBJ.remove(i);
                break;
                }}
case 2:
        int n2=OBJ.size();
        for (int i=0;i<n2;i++){
            pp=(GrObject)OBJ.get(i);
            if (pp.inside(xx, yy)) {
                pp.pause=true;
                break;
                }} 
        break;
        }
    }//GEN-LAST:event_TXTMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FileDialog dlg=new FileDialog(this,"Сохранить файл",FileDialog.SAVE);
        dlg.setFile("*.dat");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            DataOutputStream si=new DataOutputStream(new FileOutputStream(path));
            int n=OBJ.size();
            si.writeInt(n);
            for (int i=0;i<n;i++){
                GrObject pp=(GrObject)OBJ.get(i);
                si.writeUTF(pp.getClass().getName());
                pp.Save(si);
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FileDialog dlg=new FileDialog(this,"Открыть файл",FileDialog.LOAD);
        dlg.setFile("*.dat");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            DataInputStream si=new DataInputStream(new FileInputStream(path));
            int n=si.readInt();
            GrObject pp;
            while (n--!=0){
                Class cc=Class.forName(si.readUTF());
                pp=(GrObject)cc.newInstance();
                pp.Load(si);
                pp.setComponent(TXT);
                OBJ.add(pp);
                new Thread(pp).start();
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FileDialog dlg=new FileDialog(this,"Сохранить файл",FileDialog.SAVE);
        dlg.setFile("*.txt");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            BufferedWriter si=new BufferedWriter(new OutputStreamWriter(new FileOutputStream(path),"Cp1251"));
            int n=OBJ.size();
            si.write(""+n);
            si.newLine();
            for (int i=0;i<n;i++){
                GrObject pp=(GrObject)OBJ.get(i);
                si.write(pp.getClass().getName());
                si.newLine();
                pp.SaveText(si);
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FileDialog dlg=new FileDialog(this,"Открыть файл",FileDialog.LOAD);
        dlg.setFile("*.txt");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            BufferedReader si=new BufferedReader(new InputStreamReader(new FileInputStream(path),"Cp1251"));
            String ss=si.readLine();
            int n=Integer.parseInt(ss);
            GrObject pp;
            while (n--!=0){
                Class cc=Class.forName(si.readLine());
                pp=(GrObject)cc.newInstance();
                pp.setComponent(TXT);
                pp.LoadText(si);
                OBJ.add(pp);
                new Thread(pp).start();
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FileDialog dlg=new FileDialog(this,"Сохранить файл",FileDialog.SAVE);
        dlg.setFile("*.srl");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            ObjectOutputStream si=new ObjectOutputStream(new FileOutputStream(path));
            //si.writeObject(OBJ);
            int n=OBJ.size();
            si.writeInt(n);
            for (int i=0;i<n;i++){
                GrObject pp=(GrObject)OBJ.get(i);
                si.writeObject(pp);
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FileDialog dlg=new FileDialog(this,"Открыть файл",FileDialog.LOAD);
        dlg.setFile("*.srl");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            ObjectInputStream si=new ObjectInputStream(new FileInputStream(path));
            int n=si.readInt();
            GrObject pp;
            while (n--!=0){
                pp=(GrObject)si.readObject();
                OBJ.add(pp);
                pp.setComponent(TXT);
                new Thread(pp).start();
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FileDialog dlg=new FileDialog(this,"Сохранить файл",FileDialog.SAVE);
        dlg.setFile("*.xml");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try {
            OutputStreamWriter si=new OutputStreamWriter(new FileOutputStream(path),"Cp1251");
            XStream xstream = new XStream();
            Circle.setXMLParser(xstream);
            Zwezda.setXMLParser(xstream);
            GrObject.setXMLParser(xstream);
            xstream.toXML(OBJ,si);
            si.flush();
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FileDialog dlg=new FileDialog(this,"Открыть файл",FileDialog.LOAD);
        dlg.setFile("*.xml");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try	{
            BufferedReader si=new BufferedReader(new InputStreamReader(new FileInputStream(path),"Cp1251"));
            XStream xstream = new XStream();
            Circle.setXMLParser(xstream);
            Zwezda.setXMLParser(xstream);
            GrObject.setXMLParser(xstream);
            Vector<GrObject> xx=(Vector)xstream.fromXML(si);
            si.close();
            for(int i=0;i<xx.size();i++){
                GrObject pp=xx.get(i);
                OBJ.add(pp);
                pp.setComponent(TXT);
                new Thread(pp).start();
                }
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void TTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TTActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FileDialog dlg=new FileDialog(this,"Сохранить файл",FileDialog.SAVE);
        dlg.setFile("*.json");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try {
            BufferedWriter si= new BufferedWriter(new OutputStreamWriter(new FileOutputStream(path),"Cp1251"));
            Gson gson = new Gson();
            int n=OBJ.size();
            si.write(""+n);
            si.newLine();
            for (int i=0;i<n;i++){
                GrObject pp=(GrObject)OBJ.get(i);
                si.write(pp.getClass().getName());
                si.newLine();
                si.write(gson.toJson(pp));
                si.newLine();
                }
            si.flush();
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee);}
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FileDialog dlg=new FileDialog(this,"Открыть файл",FileDialog.LOAD);
        dlg.setFile("*.json");
        dlg.show();
        String path=dlg.getDirectory()+dlg.getFile();
        try {
            Gson gson = new Gson();
            BufferedReader si=new BufferedReader(new InputStreamReader(new FileInputStream(path),"Cp1251"));
            String ss=si.readLine();
            int n=Integer.parseInt(ss);
            GrObject pp;
            while (n--!=0){
                Class cc=Class.forName(si.readLine());
                pp=(GrObject)gson.fromJson(si.readLine(),cc);
                pp.setComponent(TXT);
                OBJ.add(pp);
                new Thread(pp).start();
                }
            si.close();
            }
        catch (Exception ee) { TT.setText(""+ee); }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

   public static void setUIManager(String name){
        try {
            javax.swing.UIManager.setLookAndFeel("System");
        } catch (Throwable ex) {} 
    }
    public static void main(String args[]) {
        setUIManager("Nimbus");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
        }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TT;
    private javax.swing.JTextArea TXT;
    private java.awt.Choice TYPE;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
    private int radius = 70;
}
